LFUDA changes
lbryio/reflector.go pull request #47
Opened 2020-11-27 16:04 UTC by nikooo777

and other improvements

2020-11-27 21:36 UTC, lyoshenka requested changes
a bunch of potential changes here. if you think we should put off some for now, we can discuss.

2020-11-27 21:36 UTC, lyoshenka commented on store/caching.go
> +	go func() {
this also needs a clean shutdown. like, what if its putting to the cache and a shutdown happens. we don't want a half-write or somethin.

2020-11-27 21:36 UTC, lyoshenka commented on store/caching_test.go
> +	time.Sleep(10 * time.Millisecond) //storing to cache is done async so let's give it some time
need a way to do these sync or async. at the very least, an option for the cache. ideally, some process of notifying when writes finish.

2020-11-27 21:36 UTC, lyoshenka commented on store/lfuda.go
> +var fakeTrue = []byte{'t'}
seems weird to do this. why not an actual `bool`, or an empty struct?

2020-11-27 21:36 UTC, lyoshenka commented on store/lfuda.go
> +type LFUDAStore struct {
if this is very similar to LRUStore, maybe we need a generic EvictionStrategy struct of some sort

2020-11-27 21:36 UTC, lyoshenka commented on store/lfuda.go
> +// Put stores the blob. Following LFUDA rules it's not guaranteed that a SET will store the value!!!
:+1: for the comment

2020-11-27 21:36 UTC, lyoshenka commented on store/lfuda.go
> +func (l *LFUDAStore) PutSD(hash string, blob stream.Blob) error {
why are Put and PutSD implemented differently?

2020-11-27 21:36 UTC, lyoshenka commented on store/lfuda.go
> +func (l *LFUDAStore) loadExisting(store lister, maxItems int) error {
stuff like this makes me even more confident that LRU and LFUDA should be less copy-pasted and more the same object with an eviction strategy selector

2020-11-27 21:36 UTC, lyoshenka commented on store/lfuda_test.go
> +	_, err = lfuda.Get("five")
check the blob value too?

2020-11-27 21:36 UTC, lyoshenka commented on store/lfuda_test.go
> +	log.Infof("%+v", keys)
use `t.Log()` insteade

2020-11-27 21:36 UTC, lyoshenka commented on store/lru.go
> +	go func() {
this should at least be an option, and ideally should have a way to notify that load finished. 

also needs clean shutdown

2020-11-27 21:36 UTC, lyoshenka commented on store/speedwalk/speedwalk.go
> +	logrus.Infoln("loaded LRU")
left over from testing?

2020-12-09 18:19 UTC, nikooo777 commented on store/lfuda.go
> +var fakeTrue = []byte{'t'}
the reason I did this was because the library wasn't treating a bool as a 1byte type and it would waste a lot of RAM.

I since worked with the developer of the library to address this so i believe we can go back to using a bool

2020-12-09 18:20 UTC, nikooo777 commented on store/lfuda_test.go
> +	log.Infof("%+v", keys)
ah right, this can actually be removed. it was a debug statement

2020-12-09 18:21 UTC, nikooo777 commented on store/lru.go
> +	go func() {
can I argue that a clean shutdown here doesn't matter? or is it just bad?

2020-12-09 18:21 UTC, nikooo777 commented on store/speedwalk/speedwalk.go
> +	logrus.Infoln("loaded LRU")
yes

2020-12-10 07:16 UTC, andybeletsky commented on cmd/reflector.go
> +		"enable buffer disk cache, setting max size and path where to store blobs. format is 'sizeGB:CACHE_PATH'")
What's buffer disk cache?

2020-12-10 07:19 UTC, andybeletsky commented on cmd/reflector.go
> +		"enable disk cache, setting max size and path where to store blobs. format is 'sizeGB:CACHE_PATH'")
It seems we cannot really "disable" disk cache so this has to be reworded.

2020-12-10 07:24 UTC, andybeletsky commented on store/lru.go
> +	go func() {
If you have a big cache, start this and immediately press `Ctrl+C`, what will happen? My guess is it probably won't shut down and will annoyingly keep running in the foreground.

2020-12-10 14:59 UTC, lyoshenka commented on store/lru.go
> +	go func() {
YES! this was in the back of my mind but i forgot about it. i think there's even a TODO in the code. thanks for catching it

2020-12-10 15:00 UTC, lyoshenka commented on cmd/reflector.go
> +		"enable disk cache, setting max size and path where to store blobs. format is 'sizeGB:CACHE_PATH'")
disk cache should disable-able. only hot cache is required atm

2020-12-10 15:00 UTC, lyoshenka commented on cmd/reflector.go
> +		"enable disk cache, setting max size and path where to store blobs. format is 'sizeGB:CACHE_PATH'")
in fact disk cache should be off by default

2020-12-10 15:01 UTC, lyoshenka commented on cmd/reflector.go
> +		"enable disk cache, setting max size and path where to store blobs. format is 'sizeGB:CACHE_PATH'")
also also, i thought i changed this to be the way you described: one flag to enabled and set path, second flag to set size (and there's a default size)

2020-12-22 20:10 UTC, nikooo777 commented on store/lru.go
> +	go func() {
@andybeletsky IIRC as long as the main thread returns, all routines are automatically killed in GO. I'll have to test that but I think a ctrl+c would kill it right away

2020-12-22 20:18 UTC, nikooo777 commented on cmd/reflector.go
> +		"enable buffer disk cache, setting max size and path where to store blobs. format is 'sizeGB:CACHE_PATH'")
it's an extra layer of disk caching (meant to be used on a secondary drive, like our extra 500GB nvme drive) to have faster caches. We disabled this in production because it made things worse.
My plan is to get rid of this mess and just use a yaml config file.

2021-03-10 21:23 UTC, kauffj commented
Another pair session could be in order to finally get this out...

2021-05-26 20:09 UTC, kauffj commented
:zombie:

2021-05-26 20:09 UTC, closed without merging